# Site settings
title: EFIDroid
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Android Multiboot Bootloader
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://efidroid.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  efidroid
#google_play: 'GDGX'
google_plus_com: '114053643671219382368'  # Community link
#google_plus_per: '+GDGManagua'  #Personal link
#facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

menu_main:
  option0:
    name: Wiki
    link: https://github.com/efidroid/projectmanagement/wiki
  option1:
    name: Issues
    link: https://github.com/efidroid/projectmanagement/issues
  option2:
    name: About
    link: /about

disqus: false
disqus_shortname: 'gdgmanagua'

enable_search: false

# Build settings
markdown: kramdown
